browser=chrome
url=https://www.amazon.in
username=vinnarasiv17@gmail.com
password=Joevin
implicitWait=20
headless=false
dashboardTitle=Online Shopping site in India: Shop Online for Mobiles, Books, Watches, Shoes and More - Amazon.in